### ISSUE TITLE
potential hiccup in composer.json dependencies

### ISSUE THREAD

**Issue by jimmydburr** [Maks3w/xmldsig#1]
Just fyi,

It may be just me, but I can't get composer to install your package and it's dependencies. Specifically, it stalls on the xmlsec libraries. See the below cut and paste of my command line errors followed by my composer.json.

Thanks,
# Jim...

$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fr3d/xmldsig dev-master -> satisfiable by fr3d/xmldsig[dev-master].
    - fr3d/xmldsig dev-master requires cdatazone/xmlseclibs \* -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

jburrell@JBURRELL-PC ~/Documents/Projects/dsig/dsignit
$ cat composer.json
{
        "require": {
                             "fr3d/xmldsig": "dev-master"
                        }
}

**Comment by Maks3w** [comment]
v1.1.0 has been released using the official git port of xmlseclibs

**Comment by jimmydburr** [comment]
OK, thanks for the heads-up. I'll give it a whirl.
