### ISSUE TITLE
About the install and test way.

### ISSUE THREAD

**Issue by HowquaX** [Maks3w/xmldsig#12]
Hi, Maks3W
I think that this project is so great and will help me a lot in studying xml digital signature.
so I wanna konw how should I do the install and start the test.
I have downloaded the project and put them into the xampp/htdocs.
But some problem have happened here:

Fatal error: Class 'PHPUnit_Framework_TestCase' not found in X:\xampp\htdocs\xmldsig\test\Soap\SoapClientTest.php on line 16
Fatal error: Class 'PHPUnit_Framework_TestCase' not found in X:\xampp\htdocs\xmldsig\test\Soap\SoapClientTest.php on line 16
my development environment is:
win10+Xampp（PHP 5.6 phpunit 3.7.21）

**Comment by Maks3w** [comment]
Sorry, I don't have the time for this now. Please ask your question in a Q&A site like StackOverflow
