### ISSUE TITLE
Append after element unavailable

### ISSUE THREAD

**Issue by Sardis93** [Maks3w/xmldsig#16]
First of all, thanks for a nice lib.
But there's a small problem. I need to append signature to a specific node of the xml and there's no such possibility, so i have to extend a given class.
Could you add second parameter to the [sign method](https://github.com/Maks3w/xmldsig/blob/master/src/Adapter/XmlseclibsAdapter.php#L108) and simply pass it to the [sign method of XMLSecurityDSig object](https://github.com/Maks3w/xmldsig/blob/master/src/Adapter/XmlseclibsAdapter.php#L127)?

**Comment by Maks3w** [comment]
Thanks for your suggestion. Feel free to send a Pull Request with your proposal.
