### ISSUE TITLE
How to use a private key file that has password in it?

### ISSUE THREAD

**Issue by batata004** [Maks3w/xmldsig#18]
Hi,

I am using this library to sign a XML but I am having a problem. The exported file has password, how do I workaround it? So far I am using this code.

$xmlTool = new FR3D\XmlDSig\Adapter\XmlseclibsAdapter();
$xmlTool->setPrivateKey(file_get_contents('keys/private.pem'));

**Comment by Maks3w** [comment]
Please use the issue tracker just for report real issues with the code. Your questions are better suitable for a Q&A site like StackOverflow
