### ISSUE TITLE
Deprecated package

### ISSUE THREAD

**Issue by FraGoTe** [Maks3w/xmldsig#2]
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package cdatazone/xmlseclibs could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting

**Comment by Maks3w** [comment]
v1.1.0 has been released using the official git port of xmlseclibs
