### ISSUE TITLE
Example of use

### ISSUE THREAD

**Issue by vesvello** [Maks3w/xmldsig#7]
I know its not an issue, but I am newbie on this and I coudnt find where post my question.

I have very limited experience with coding but i would be very grateful if you can provide me an example of code to call the functions to work with your code, because I need to sign a xml and I have no idea how to work with your code.

Sorry in advance for my ignorance

**Comment by Maks3w** [comment]
You can take a look to the test suite
https://github.com/Maks3w/xmldsig/blob/master/test/Adapter/AdapterInterfaceTestTrait.php#L49
