### ISSUE TITLE
How to Add X509Certificate

### ISSUE THREAD

**Issue by wallii** [Maks3w/xmldsig#8]
Hello I use this library for signing xml documents with certificate i can't find how to sign the xml in the format  of 

<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
  <SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
    <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>EpRiYzJ7rtywFsX3MCju0b8d2wQ=</DigestValue></Reference></SignedInfo><SignatureValue>mv0sqqvF4Xwyojjh8wEleYl/QPW4C0AAGXAqML5dmm6XrezgaEHW0BNDTe1nfdDcAyGun3MYEy3jYH1bvgiPOSsz2qX/lWRymvX/IkILwFv02/zETT2NYeDmAPfT7jSLt0jnuAZ1zFw7vY/jsPyoYx6dGKkX7xDYsWc0lGCS0AM=</SignatureValue>
<KeyInfo><X509Data><X509Certificate>MIIDHzCCAoigAwIBAgIJAKQGxAcskoRVMA0GCSqGSIb3DQEBBQUAMGkxCzAJBgNVBAYTAklOMQ4wDAYDVQQIEwVERUxISTEXMBUGA1UEBxMOSVRPLCBLT1RBIFJPQUQxDjAMBgNVBAoTBUNEU0NPMREwDwYDVQQLEwhDRFNDTyBIUTEOMAwGA1UEAxMFQ0RTQ08wHhcNMTUwOTA5MTExMzE1WhcNMTYwOTA4MTExMzE1WjBpMQswCQYDVQQGEwJJTjEOMAwGA1UECBMFREVMSEkxFzAVBgNVBAcTDklUTywgS09UQSBST0FEMQ4wDAYDVQQKEwVDRFNDTzERMA8GA1UECxMIQ0RTQ08gSFExDjAMBgNVBAMTBUNEU0NPMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC6905X4RXREf/+ZXe0Bhc4M49cCcg7sBK5ZmypHZ2Aaz9T0z456TZ4X7pGWNANJZ3GCmqIZH1o9k8zMMDghtcEKp4gVridei8Gr52XF94i465WyHeRn3n0UGmAm4CJa/gSkz3OL5ttBS2wD1v77mJedFeen8+J6Ga2vawnhS6LkQIDAQABo4HOMIHLMB0GA1UdDgQWBBTCjmDcyWWV306y1l+Mc1gu8audrDCBmwYDVR0jBIGTMIGQgBTCjmDcyWWV306y1l+Mc1gu8audrKFtpGswaTELMAkGA1UEBhMCSU4xDjAMBgNVBAgTBURFTEhJMRcwFQYDVQQHEw5JVE8sIEtPVEEgUk9BRDEOMAwGA1UEChMFQ0RTQ08xETAPBgNVBAsTCENEU0NPIEhRMQ4wDAYDVQQDEwVDRFNDT4IJAKQGxAcskoRVMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAb1kkFWKByuiapHIOWpihILx7vxb6AqQr5mf4rZdTSMQqBRF2bAvfswr4vnE6tb5RmFrTa5O2yZfCgaVtDmGuUGKTfxTD11fIZ1CAWChwfSWDYOPXpwYhZ/SnHVBGvRMQT6sksDlkaLrEMZHkTyDA89hm6Hzh9ic5k0PyFq7u7og=</X509Certificate></X509Data><KeyValue><RSAKeyValue><Modulus>uvdOV+EV0RH//mV3tAYXODOPXAnIO7ASuWZsqR2dgGs/U9M+Oek2eF+6RljQDSWdxgpqiGR9aPZPMzDA4IbXBCqeIFa4nXovBq+dlxfeIuOuVsh3kZ959FBpgJuAiWv4EpM9zi+bbQUtsA9b++5iXnRXnp/Piehmtr2sJ4Uui5E=</Modulus><Exponent>AQAB</Exponent></RSAKeyValue></KeyValue></KeyInfo></Signature>
please help

**Comment by Maks3w** [comment]
Clarify your question

**Comment by wallii** [comment]
Actually i want to add more information on sign xml 

<X509Certificate>, <RSAKeyValue><Modulus>, and </Exponent> how to add this

**Comment by Maks3w** [comment]
https://github.com/Maks3w/xmldsig/blob/master/test/Adapter/AdapterInterfaceTestTrait.php#L47

**Comment by wallii** [comment]
How i Add certificate , actually i have a cdsco.p12 file in this file i found certificate and private key, i generate public key from certificate but how i add certificate from code
