### ISSUE TITLE
usecase about Reference identifier with uppercase

### ISSUE THREAD

**Issue by zogs** [Maks3w/xmldsig#9]
Hello,

I found your library useful, but when i tried to validate my signature, i found that its fail cause to a uppercase identifier. I contacted robrichards/xmlseclibs thinking the problem comes from his library but in fact this usecase is taking care of. See his answer here [https://github.com/robrichards/xmlseclibs/issues/91].
However, its seems not possible to use this solution within your library. Or am i wrong ?

**Comment by Maks3w** [comment]
You are right, it's not possible add that paremeter without rewrite the whole method.

This could be easily achieved extracting `new XMLSecurityDSig()` to a protected method called `createXmlSecurityDSig` so you can override that method and append any additional setting you need.

Do you want to send a PR with the modifications?

**Comment by zogs** [comment]
Ok, i will. Maybe later this week.
thx

**Comment by Maks3w** [comment]
Released with 2.1
